title: Cowspeak
email: cowspeak@protonmail.com
description: >-
  cowspeak - Display an animal with a random quote or your own text. on your linux terminal.
# baseurl for github.io
baseurl: "/cowspeak"
# baseurl for testing on localhost
baseurl: ""
url: ""
github_username:  Souravgoswami

theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/Distributions/deb"
    values:
      img_deb: true

  - scope:
      path: "assets/Distributions/others"
    values:
      img_others: true

  - scope:
      path: "assets/Distributions/arch"
    values:
      img_arch: true
