title: Cowspeak
email: cowspeak@protonmail.com
description: >-
  cowspeak - Display an animal with a random quote or your own text. on your linux terminal.
baseurl: "cowspeak-page"
url: ""
github_username:  cowspeak

theme: minima
plugins:
  - jekyll-feed
